### ISSUE TITLE
Results showing duplicate inspections

### ISSUE THREAD

**Issue by paul-gene** [magento/magento-coding-standard#98] opened 2019-05-17 14:53 UTC
I have cloned down the repo, and added the ruleset to PHPCS.

In PHPStorm, I have selected Magento2 ruleset.

When I run the inspection on a file, it shows duplicate results for the same sniff, please see attached screenshot.

<img width="845" alt="Screen Shot 2019-05-17 at 15 52 46" src="https://user-images.githubusercontent.com/47739147/57936430-d9372c80-78bb-11e9-8181-2c7af3a1dfab.png">

**Comment by lenaorobei** [comment] 2019-05-17 17:05
Hello @paul-gene.

I cannot reproduce this bug.
<img width="898" alt="Screen Shot 2019-05-17 at 12 01 20 PM" src="https://user-images.githubusercontent.com/17548019/57944137-9bc2a700-789b-11e9-8096-cf16b70ea113.png">
My only guess is that you have 2 `button.phtml` files in different namespaces with same issue. Could you please double check that.

**Comment by lenaorobei** [comment] 2019-05-21 21:41
Closing this issue since no feedback provided.

@paul-gene fell free to reopen it if you feel like it is coding standard bug.

**Closed by lenaorobei** 2019-05-21 21:41 UTC
Labels: bug

**Comment by esprit-dev** [comment] 2019-07-22 09:50
Hello, i reproduce the same issue. All warning are duplicated. Maybe a bug ? 
PhpStorm phpcs is configure with this file : dev/tests/static/framework/Magento/ruleset.xml
My magento version : 2.3.2

<img width="737" alt="Capture d’écran 2019-07-22 à 11 49 39" src="https://user-images.githubusercontent.com/7630693/61623401-dfa8a280-ac76-11e9-83f3-f6a2f72074a1.png">


Thx

**Comment by larsroettig** [comment] 2019-07-22 09:56
Hi @esprit-dev, 
which PhpStorm version you are using? For it looks like a bug from PhpStorm.

**Comment by esprit-dev** [comment] 2019-07-22 10:03
Hi @larsroettig 
Here my phpstorm version :
- PhpStorm 2019.1.2
- Build #PS-191.7141.52, built on May 8, 2019
- JRE: 1.8.0_202-release-1483-b49 x86_64
- JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
- macOS 10.14.3

**Comment by larsroettig** [comment] 2019-07-22 10:10
PhpStorm 2019.1.3 is already stable pls update and try out I can not reproduce

**Comment by esprit-dev** [comment] 2019-07-22 12:22
Thx for your answer. Update to 2019.1.3 does not resolve problem...

New input that can help a little : problem started after upgrading to Magento 2.3.2 : the ruleset file is now referencing Coding Standard module : 
`<rule ref="./../../../../../vendor/magento/magento-coding-standard/Magento2"/>`

I had no issue with Magento 2.3.1 (ruleset was standalone / no include / full rules)

**Comment by agkozak** [comment] 2019-07-23 15:01
There's a bug report over on the PHPStorm YouTrack:

https://youtrack.jetbrains.com/issue/WI-46317
