### ISSUE TITLE
Delete ConstantUsageSniff (Magento2.Translation.ConstantUsage) from coding standard

### ISSUE THREAD

**Issue by likemusic** [magento/magento-coding-standard#97] opened 2019-05-16 23:25 UTC
### Description
ConstantUsageSniff (Magento2.Translation.ConstantUsage) should be deleted because it encourage code duplication (what is bad practice) by message: `Constants are not allowed as the first argument of translation function, use string literal instead`.

### Expected behavior
Don't inspect if constants used as first argument of translation function.

### Benefits
Less code duplicates - less bugs.

### Additional information
Seems that this Sniff and code recomendation exists because magento command `bin/magento i18n:collect-phrases` in current implementation couldn't extract strings from constants.

Some ideas how to fix it:
- implement constant resolving in `i18n:collect-phrases`  (maybe by [nikic/PHP-Parser](https://github.com/nikic/PHP-Parser)) - the most obvious but difficult for implementation way;
- extract constants used in translation function that would be inspected manually by developers (with pointing to file and line) by command line option - the most easy for implementation way;
- extract all strings from files or just strings that not used in translation function by command line option;
- extract all constant strings by command line option;

**Comment by lenaorobei** [comment] 2019-06-07 14:26
Hi @likemusic,

Thanks for raising this issue. You're right, the root cause of this issue is hidden under `i18n:collect-phrases`. I suggest opening issue or even proposal (PR) in the [magento/architecture](https://github.com/magento/architecture) repository and describe the problem. Since there is direct correlation the referenced static check will be removed once `i18n:collect-phrases` will be improved.

Thanks.

**Comment by orlangur** [comment] 2019-07-24 16:16
Until `bin/magento i18n:collect-phrases` behavior is changed there is nothing to change here from coding standard perspective, why keep this issue open?

**Comment by Nolwennig** [comment] 2019-07-28 11:26
@orlangur maybe for to occur a chain reaction when `i18n:collect-phrases` behavior will be update ;-)

@lenaorobei at this time, nobody open issue or PR in the [magento/architecture repository](https://github.com/magento/architecture) isn't  ?

**Comment by lenaorobei** [comment] 2019-07-30 16:43
@Nolwennig unfortunately isse was not opened.

Closing this issue since the root cause is in `bin/magento i18n:collect-phrases` behaviour.

@likemusic feel free to reopen or create the new one when the enhancement of `bin/magento i18n:collect-phrases` will be approved in the [magento/architecture](https://github.com/magento/architecture) repository.

**Closed by lenaorobei** 2019-07-30 16:43 UTC
Labels: enhancement, need to discuss
